name: Deploy NodeJs
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: docker.io  # Alterado para o Docker Hub
  REPO: cayke1/paymepls-backend/paymepls  # Nome do repositório no Docker Hub
  CONTAINER: paymepls

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO }}:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}:latest

  deploy:
    needs: [push_to_registry]
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Login to Docker Hub
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}"

      - name: Pull latest container from Docker Hub
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker pull ${{env.REGISTRY}}/${{env.REPO}}:latest"

      - name: Stop deployed container
        continue-on-error: true
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker stop ${{env.CONTAINER}}"
      
      - name: Remove deployed container
        continue-on-error: true
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker rm ${{env.CONTAINER}}"
      
      - name: Start docker container from Docker Hub
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker run -p 3395:3395 -d --restart unless-stopped --name=${{env.CONTAINER}} ${{env.REGISTRY}}/${{env.REPO}}:latest"
        
      - name: Logout from Docker Hub
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker logout"
